// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"Yami_SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"ZE - Key Mapper","status":true,"description":"This plugin lets you control the keys on the keyboard, and how they're mapped to the game.\r\n\r\n<pluginID ZE - Key Mapper>","parameters":{"0":"0","1":"num1","2":"num2","3":"3","4":"4","5":"5","6":"6","7":"7","8":"8","9":"9","Tab":"tab","Backspace":"backspace","Enter":"ok","Shift":"shift","Control":"control","Alt":"control","Pause":"pause","Capslock":"caps","Escape":"tab","Space":"ok","Pageup":"pageup","Pagedown":"pagedown","Home":"home","End":"end","Left":"left","Up":"up","Right":"right","Down":"down","Print Screen":"prntscrn","Insert":"escape","Delete":"delete","A":"left","B":"b","C":"c","D":"right","E":"ok","F":"f","G":"g","H":"h","I":"i","J":"j","K":"k","L":"l","M":"m","N":"n","O":"o","P":"p","Q":"p","R":"r","S":"down","T":"t","U":"u","V":"v","W":"up","X":"x","Y":"y","Z":"z","Semicolon":"semicolon","Equals":"equals","Minus":"minus","Super":"super","Media":"media","Num0":"num0","Num1":"num1","Num2":"num2","Num3":"num3","Num4":"num4","Num5":"num5","Num6":"num6","Num7":"num7","Num8":"num8","Num9":"num9","Num*":"multiply","Num+":"add","Num-":"subtract","Num.":"decimal","Num/":"divide","F1":"F1","F2":"F2","F3":"F3","F4":"F4","F5":"F5","F6":"F6","F7":"F7","F8":"F8","F9":"debug","F10":"F10","F11":"F11","F12":"F12","Numlock":"numlock","Scroll Lock":"scrollock","Comma":"comma","Period":"period","Slash":"slash","Backtick":"tilde","Open Brace":"[","Backslash":"\\","Closing Brace":"]","Quote":"'"}},
{"name":"GALV_EventSpawner","status":true,"description":"(v.1.8) Spawn events from a specified spawn map to a desired location.","parameters":{"Spawn Map Id":"2"}},
{"name":"BMM_Globals","status":true,"description":"Store globally used variables here","parameters":{}},
{"name":"BMM_Overrides","status":true,"description":"Handles the major overrides and disables unneeded features of the engine","parameters":{"MovementInputBlock":"true"}},
{"name":"BMM_Transmission","status":true,"description":"Handles state management for the game","parameters":{}},
{"name":"BMM_Intake","status":true,"description":"Handles keyboard input and ability cooldowns","parameters":{}},
{"name":"BMM_TimingBelt","status":true,"description":"Handles timing system","parameters":{}},
{"name":"BMM_Hybrid","status":true,"description":"Handles core gameplay loops and syncronization","parameters":{}},
{"name":"BMM_Powertrain","status":true,"description":"Handles and stores sequenced classes","parameters":{}},
{"name":"Johnas_Show_Timer","status":true,"description":"Shows the turn timer and time remaining","parameters":{}},
{"name":"Johnas_Show_Hearts","status":true,"description":"Shows the number of hearts the player has (Currently 0 - 6)","parameters":{}},
{"name":"Johnas_Show_Attack_Telegraph","status":true,"description":"Shows the affected areas of an enemy's attacks","parameters":{"":""}},
{"name":"Johnas_testCallingFunction","status":true,"description":"","parameters":{}},
{"name":"Johnas_Show_Ability_Cooldowns","status":true,"description":"","parameters":{}},
{"name":"Johnas_Show_Boss_Info","status":true,"description":"","parameters":{}},
{"name":"Shaz_TileChanger","status":true,"description":"Change tiles on map or copy tiles from another map","parameters":{}},
{"name":"MBS_MapZoom","status":true,"description":"Makes it possible to zoom in and out the game map\n\n<MBS MapZoom>","parameters":{"Reset on map change":"true","Default zoom":"1.0"}},
{"name":"GALV_CamControl","status":true,"description":"Allows greater control over where the game camera is focused. View HELP for plugin commands.","parameters":{"Tile Size":"48"}},
{"name":"GALV_MapAnimEffects","status":true,"description":"Enhance the usability of animations and use them to create effects when characters stand on regions.","parameters":{"Region Effects":"7,10,a-fly | 2,9,a+fly | 5,11,a","Followers":"true"}}
];
